baseURL = "https://blog.navyd.xyz"
title = "navyd的个人博客"
# paginate = 5
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = "G-JKFZ31HBBS"

ignoreFiles = ['content/res/*']
languageCode = "zh-cn"
defaultContentLanguage = "zh"
hasCJKLanguage = true
# https://gohugo.io/content-management/summaries/#hugo-defined-automatic-summary-splitting
summaryLength = 100

# pygmentsOptions = "linenos=table"
# pygmentsCodefences = true
# pygmentsUseClasses = true
# pygmentsCodefencesGuessSyntax = true

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true

# [permalinks]
# post = "/post/:year/:month/:day/:filename/"
# archive = "/archive/:year/:month/:day/:filename/"

[minify]
disableXML = true
minifyOutput = true

[outputs]
# JSON for search fuse.js
home = ['HTML', 'JSON', 'RSS']

[params]
env = "production"                           # to enable google analytics, opengraph, twitter-cards and schema.
title = "ExampleSite"
description = "ExampleSite description"
keywords = ["Blog", "Portfolio", "PaperMod"]
author = ["navyd"]                           # multiple authors
images = []                                  # ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "2006-01-02"
defaultTheme = "auto"                        # dark, light
disableThemeToggle = true

ShowReadingTime = true
ShowShareButtons = false              # Displays Share Buttons at Bottom of each post
ShowPostNavLinks = true               # Adds a Previous / Next post suggestion under a single post
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.assets]
# disableHLJS: true # to disable highlight.js
# disableFingerprinting: true
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.ico"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/favicon.ico"

[params.label]
text = "首页"
icon = "/android-chrome-512x512.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "navyd的个人博客"
Content = "Welcome to my blog"

# [[params.socialIcons]]
# name = "twitter"
# url = "https://twitter.com/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/navyd"

[params.analytics.google]
# ga
SiteVerificationTag = "G-JKFZ31HBBS"

# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"

# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

[params.cover]
# hidden = true
# hiddenInList = true
# hiddenInSingle = true
useFirstImageIfNone = true

[params.editPost]
URL = "https://github.com/NavyD/navyd.github.io/tree/main/content"
Text = "修改建议"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 30
