[tools]
python = "3.13"
uv = "0.5"
watchexec = "2.3"

[env]
_.python.venv = { path = ".venv", create = true }
_.file = ".env"
# NOTE: python venv未被task中加载，导致无法使用venv的python
_.path = ["{{config_root}}/.venv/{% if os() == 'windows' %}Scripts{% else %}bin{% endif %}"]

# uv pip在所有索引中搜索每个包，并从组合的候选版本中选择最佳版本
# https://docs.astral.sh/uv/configuration/indexes/#searching-across-multiple-indexes
UV_INDEX_STRATEGY = "unsafe-best-match"

[settings]
# windows_default_inline_shell_args = "powershell -NoProfile -NonInteractive -Command"
# windows_default_inline_shell_args = "python -c"
# experimental = true

[tasks.init-venv]
description = "init build venv"
hide = true
run = 'uv sync --all-groups'
sources = ["uv.lock", "pyproject.toml"]
outputs.auto = true

[tasks.build]
# shell = "python -c"
description = "build dyn data"
sources = ["content/posts/**/*.md"]
outputs = ["data/posts/posts.json"]
depends = ["init-venv"]
# 关闭server和build可以同时进行，不用等待
# wait_for = ["close-server"]
run = 'hugodynctx posts -v'

[tasks.close-server]
shell = "python -c"
description = "close hugo server"
run = '''
import psutil
print("Checking if hugo server exists")
for p in psutil.process_iter():
    name = p.name()
    if (psutil.WINDOWS and name.lower() == "hugo.exe") or (
        not psutil.WINDOWS and name == "hugo"
    ):
        print(f"Killing process {p}")
        p.kill()
        break
'''

[tasks.server]
shell = "python -c"
description = "start hugo server in background"
depends = ["close-server", "build"]
# start-Process -FilePath (Get-Command hugo).Path -ArgumentList server -WindowStyle Hidden -RedirectStandardOutput $(New-TemporaryFile) -RedirectStandardError $(New-TemporaryFile)
sources = ["content/**", "layouts/**", "themes/**"]
run = '''
import subprocess
import sys

command = [
    "hugo",
    "server",
    "--navigateToChanged",
    "--buildDrafts",
    "--environment",
    "production",
    "--port",
    "1313",
]
stdout_path = ".hugo-server.log"
# stderr_path = ".hugo-server.err.log"
# open(stderr_path, "wb") as stderr,
with open(stdout_path, "wb") as stdout:
    stderr = stdout
    if sys.platform == "win32":
        proc = subprocess.Popen(
            command,
            stdin=subprocess.DEVNULL,
            stdout=stdout,
            stderr=stderr,
            # creationflags=subprocess.DETACHED_PROCESS,
            creationflags=subprocess.CREATE_NEW_PROCESS_GROUP,
            # close_fds=True,
        )
    else:
        proc = subprocess.Popen(
            command,
            start_new_session=True,
            stdin=subprocess.DEVNULL,
            stdout=stdout,
            stderr=stderr,
        )
'''
