name: github pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main # Set a branch to deploy
  workflow_dispatch:

env:
  # NOTE: 不要写为 `~/.cache` 会无效
  UV_CACHE_DIR: /tmp/.cache/uv
  MISE_ENV: ci

# Create your workflow: https://github.com/peaceiris/actions-hugo#getting-started
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Cache mise
        id: cache-mise
        if: ${{ env.ACT }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/mise
          key: act-${{runner.os}}-mise-${{hashFiles('mise.*.toml', 'mise.toml')}}
          restore-keys: |
            act-${{runner.os}}-mise-${{hashFiles('mise.*.toml', 'mise.toml')}}
            act-${{runner.os}}-mise-
      - uses: jdx/mise-action@v2
      # https://docs.astral.sh/uv/guides/integration/github/#caching
      - name: Restore uv cache
        id: uv-cache
        uses: actions/cache@v4
        with:
          path: ${{env.UV_CACHE_DIR}}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}
      - name: Init venv with uv
        if: ${{ steps.uv-cache.outputs.cache-hit != 'true' }}
        run: uv venv .venv && uv sync
      - uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Build dynamic posts
        run: uv run hugodynctx posts -v
      - name: Minimize uv cache
        run: uv cache prune --ci
      - name: Build
        run: hugo --minify --environment production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ !env.ACT && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # 在gh-pages分支只保留最后一個提交，避免过去的pages提交增加仓库大小
          force_orphan: true
          # TODO: 自定义域名
          # cname: blog.navyd.xyz
